### ISSUE TITLE
"Cron job" update cycle mode

### ISSUE THREAD

**Issue by ArcticSpaceFox** [ArcticSpaceFox/aoc_bot#7]
## What should this do?

Should be `optional`, runs an update in a specifed time frame and sends update to discord

**Comment by dnaka91** [comment]
This should be doable fairly easy. We would just need to spin up a `tokio` ticker that triggers the board creation regularly.
Only blocker is that the current event handling needs some rework for this. What I mean is that it would be good to abstract away the event sender and handler/receiver so that not only the Discord library can send us messages but we can trigger it from the ticker as well.

So the handler just gets its channel to receive events on and handle them. And the sender part would be cloned and passed to all components that need to send events to the handler.

That means we would have to create our own enums and structs that represent the possible messages that go through the channel and have to map from the Discord events to our structures.

**Comment by ArcticSpaceFox** [comment]
#25
